version: '2.3'
services:
  micro:
    image: micro
    ports:
      - "8888:8080"
    depends_on:
        micro-2:
          condition: service_healthy

  micro-2:
    image: micro
    ports:
      - "8889:8080"
    healthcheck:
       test: [ "CMD" ,"curl", "-f", "http://localhost:8080/user/list"]
       interval: 10s
       retries: 3
       start_period: 10s
