version: '2.3'
services:
  postgresdb:
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: app
      POSTGRES_PASSWORD: app
      POSTGRES_DB: testdb
  app:
    image: cm/bajerska:1.8
    ports:
      - "8080:8080"
    depends_on:
      - postgresdb
volumes:
  db-data:

