version: '2.3'
services:
  postgresdb:
    image:  postgres:10.10
    restart: always
    environment:
      POSTGRES_USER: app
      POSTGRES_PASSWORD: app
      POSTGRES_DB: testdb
#    volumes:
#      - ./schema.sql:/docker-entrypoint-initdb.d/schema.sql
#      - ./data.sql:/docker-entrypoint-initdb.d/data.sql
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -d testdb -U app"]
      interval: 10s
      retries: 10
  app:
    image: cm/bajerska:1.8
    ports:
      - "8080:8080"
    healthcheck:
      test: [ "CMD" ,"curl", "-f", "http://localhost:8080/user/list"]
      interval: 10s
      retries: 6
    depends_on:
      postgresdb:
          condition: service_healthy
  client:
    image: zbrestclient
    environment:
      - ADDRESS=192.168.0.150:8080/user/list
    depends_on:
      app:
          condition: service_healthy



